src/WebApp/Controllers/CategoriesController.cs
using CoreBusiness;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using UseCases.Interfaces.Categories;

namespace WebApp;

[Authorize(Policy = "Admin")] // Only authorize users can access the endpoints
public class CategoriesController : Controller
{
    // Dependency Injection
    private readonly IViewCategoriesUseCase viewCategoriesUseCase; // Violation _
    private readonly IViewSelectedCategoryUseCase _viewSelectedCategoryUseCase;
    private readonly IEditCategoryUseCase _editCategoryUseCase;
    private readonly IAddCategoryUseCase _addCategoryUseCase;
    private readonly IDeleteCategoryUseCase _deleteCategoryUseCase;

    public CategoriesController(
        IViewCategoriesUseCase viewCategoriesUseCase,
        IViewSelectedCategoryUseCase viewSelectedCategoryUseCase,
        IEditCategoryUseCase editCategoryUseCase,
        IAddCategoryUseCase addCategoryUseCase,
        IDeleteCategoryUseCase deleteCategoryUseCase)
    {
        this.viewCategoriesUseCase = viewCategoriesUseCase;
        _viewSelectedCategoryUseCase = viewSelectedCategoryUseCase;
        _editCategoryUseCase = editCategoryUseCase;
        _addCategoryUseCase = addCategoryUseCase;
        _deleteCategoryUseCase = deleteCategoryUseCase;
    }
    public IActionResult Index()
    {
        var categories = viewCategoriesUseCase.Execute();
        return View(model: categories);
    }

    // [FromRoute] id: id data is coming from route, therefore /Categories/Edit?Id=1 will
    // fail to do model binding from query.
    // BY default ASP.NET will locate data from all the 5 Routes.
    [HttpGet] // Default
    public IActionResult Edit(int? id) // nullable integer; default value is null not zero
    {
        // if (id.HasValue)
        //     return new ContentResult { Content = id.ToString() }; // returns value of id; Categories/Edit/{id?}
        // else
        //     return new ContentResult { Content = "NO CONTENT; id is null" };

        // Used by partial view to identify 'Edit' or 'Add'
        ViewBag.Action = "Edit"; // NOTE: Case sensitive

        var category = _viewSelectedCategoryUseCase.Execute(id: id ?? 0);

        return View(model: category); // viewName is optional
    }

    [HttpPost] // Handles POST request
    public IActionResult Edit(Category category)
    {
        // Checking state of model and its values (i.e Category)
        if (ModelState.IsValid)
        {
            _editCategoryUseCase.Execute(id: category.Id, category: category);
            return RedirectToAction(actionName: nameof(Index));
        }

        ViewBag.Action = "Edit"; // Required for partial to be rendered correctly

        // On invalid form submission, show user Edit with the
        // invalid data (entered inside fields)
        return View(model: category);
    }

    [HttpGet]
    public IActionResult Add()
    {
        // Used by partial view to identify 'Edit' or 'Add'
        ViewBag.Action = "Add"; // NOTE: Case sensitive

        return View(viewName: "Add"); // viewName is optional if it is same as controller method name
    }

    [HttpPost]
    public IActionResult Add([FromForm] Category category)
    {
        if (ModelState.IsValid)
        {
            _addCategoryUseCase.Execute(category: category);
            return RedirectToAction(actionName: nameof(Index));
        }

        ViewBag.Action = "Add"; // Required for partial to be rendered correctly

        return View(viewName: "Add", model: category);
    }

    public IActionResult Delete(int id)
    {
        _deleteCategoryUseCase.Execute(id: id);
        return RedirectToAction(actionName: nameof(Index));
    }
}

src/WebApp/Controllers/ProductsController.cs
using CoreBusiness;

using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using UseCases.Interfaces.Categories;
using UseCases.Interfaces.Products;

using WebApp.ViewModels;

namespace WebApp.Controllers;

[Authorize(Policy = "Admin")]
public class ProductsController : Controller
{
    // Products
    private readonly IViewProductsUseCase _viewProductsInterface;
    private readonly IViewSelectedProductUseCase _viewSelectedProductUseCase;
    private readonly IAddProductUseCase _addProductUseCase;
    private readonly IEditProductUseCase _editProductUseCase;
    private readonly IDeleteProductUseCase _deleteProductUseCase;

    // Categories
    private readonly IViewCategoriesUseCase _viewCategoriesUseCase;


    public ProductsController(
        IViewProductsUseCase viewProductsInterface,
        IViewSelectedProductUseCase viewSelectedProductUseCase,
        IViewProductsByCategoryIdUseCase viewProductsByCategoryUseCase,
        IAddProductUseCase addProductUseCase,
        IEditProductUseCase editProductUseCase,
        IDeleteProductUseCase deleteProductUseCase,
        IViewCategoriesUseCase viewCategoriesUseCase)
    {
        _viewProductsInterface = viewProductsInterface;
        _viewSelectedProductUseCase = viewSelectedProductUseCase;
        _addProductUseCase = addProductUseCase;
        _editProductUseCase = editProductUseCase;
        _deleteProductUseCase = deleteProductUseCase;
        _viewCategoriesUseCase = viewCategoriesUseCase;
    }

    public IActionResult Index()
    {
        var products = _viewProductsInterface.Execute(loadCategory: true);
        return View(viewName: "Index", model: products);
    }

    public IActionResult Add()
    {
        ViewBag.Action = "Add";

        var productViewProduct = new ProductViewModel
        {
            Categories = _viewCategoriesUseCase.Execute()
        };
        return View(viewName: "Add", model: productViewProduct);
    }

    [HttpPost]
    public IActionResult Add(ProductViewModel productViewModel)
    {
        if (ModelState.IsValid)
        {
            _addProductUseCase.Execute(product: productViewModel.Product);
            return RedirectToAction(actionName: nameof(Index));
        }

        ViewBag.Action = "Add";

        productViewModel.Categories = _viewCategoriesUseCase.Execute();
        return View(viewName: "Add", model: productViewModel);
    }

    public IActionResult Edit(int id)
    {
        ViewBag.Action = "Edit";

        var productViewModel = new ProductViewModel
        {
            Product = _viewSelectedProductUseCase.Execute(id: id) ?? new Product(), // if null create a new instance of Product
            Categories = _viewCategoriesUseCase.Execute()
        };

        return View(viewName: "Edit", model: productViewModel);
    }

    [HttpPost]
    public IActionResult Edit(ProductViewModel productViewModel)
    {
        if (ModelState.IsValid)
        {
            _editProductUseCase.Execute(
                id: productViewModel.Product.Id,
                product: productViewModel.Product);
            return RedirectToAction(actionName: nameof(Index));
        }

        ViewBag.Action = "Edit";

        productViewModel.Categories = _viewCategoriesUseCase.Execute();
        return View(viewName: "Edit", model: productViewModel);
    }

    public IActionResult Delete(int id)
    {
        _deleteProductUseCase.Execute(id: id);
        return RedirectToAction(actionName: nameof(Index));
    }
}

src/WebApp/Controllers/SalesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using UseCases.Interfaces.Categories;
using UseCases.Interfaces.Products;
using UseCases.Interfaces.Transactions;

namespace WebApp.Controllers;

[Authorize(Policy = "AdminOrSeller")]
public class SalesController : Controller
{
    // Categories
    private readonly IViewCategoriesUseCase _viewCategoriesUseCase;
    // Products
    private readonly IViewSelectedProductUseCase _viewSelectedProductUseCase;
    private readonly IViewProductsByCategoryIdUseCase _viewProductsByCategoryUseCase;
    private readonly IEditProductUseCase _editProductUseCase;
    // Transactions
    private readonly IAddTransactionUseCase _addTransactionUseCase;

    public SalesController(
        IViewCategoriesUseCase viewCategoriesUseCase,
        IViewSelectedProductUseCase viewSelectedProductUseCase,
        IEditProductUseCase editProductUseCase,
        IAddTransactionUseCase addTransactionUseCase,
        IViewProductsByCategoryIdUseCase viewProductsByCategoryUseCase)
    {
        _viewCategoriesUseCase = viewCategoriesUseCase;
        _viewSelectedProductUseCase = viewSelectedProductUseCase;
        _editProductUseCase = editProductUseCase;
        _addTransactionUseCase = addTransactionUseCase;
        _viewProductsByCategoryUseCase = viewProductsByCategoryUseCase;
    }

    public IActionResult Index()
    {
        var salesViewModel = new SalesViewModel
        {
            Categories = _viewCategoriesUseCase.Execute()
        };

        return View(viewName: "Index", model: salesViewModel);
    }

    public IActionResult Sell(SalesViewModel salesViewModel)
    {
        if (ModelState.IsValid)
        {
            var prod = _viewSelectedProductUseCase.Execute(id: salesViewModel.SelectedProductId);
            if (prod != null)
            {
                _addTransactionUseCase.Execute(
                    User.Identity?.Name,
                    salesViewModel.SelectedCategoryId,
                    prod.Name,
                    prod.Price.HasValue ? prod.Price.Value : 0,
                    prod.Quantity.HasValue ? prod.Quantity.Value : 0,
                    salesViewModel.QuantityToSell
                );

                // Decrease the product quantity
                prod.Quantity -= salesViewModel.QuantityToSell;

                // Update the product
                // ProductsRepository.UpdateProduct(salesViewModel.SelectedProductId, product: prod); // OLD
                _editProductUseCase.Execute(id: salesViewModel.SelectedProductId, product: prod);
            }
        }

        // In case validation fails

        // Get the product
        var product = _viewSelectedProductUseCase.Execute(id: salesViewModel.SelectedProductId);

        // Get the category of the product
        salesViewModel.SelectedCategoryId = (product?.CategoryId == null) ? 0 : product.CategoryId.Value;
        salesViewModel.Categories = _viewCategoriesUseCase.Execute();

        return View(viewName: "Index", model: salesViewModel);
    }

    // Returns partial view (Contains product detail)
    public IActionResult SellProductPartial(int id)
    {
        var product = _viewSelectedProductUseCase.Execute(id: id);
        return PartialView(viewName: "_SellProduct", model: product);
    }

    // Returns partial view (Contains list of products based on category)
    public IActionResult ProductsByCategoryPartial(int categoryId)
    {
        var products = _viewProductsByCategoryUseCase.Execute(id: categoryId);
        return PartialView(viewName: "_Products", model: products);
    }
}

src/WebApp/Controllers/TransactionsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

using UseCases.Interfaces.Transactions;

using WebApp.ViewModels;

namespace WebApp.Controllers;

[Authorize(Policy = "AdminOrManager")]
public class TransactionsController : Controller
{
    // Transactions
    private readonly ISearchTransactionsUseCase _searchTransactionsUseCase;

    public TransactionsController(ISearchTransactionsUseCase searchTransactionsUseCase)
    {
        _searchTransactionsUseCase = searchTransactionsUseCase;
    }

    public IActionResult Index()
    {
        return View(viewName: "Index", model: new TransactionsViewModel());
    }

    public IActionResult Search(TransactionsViewModel transactionViewModel)
    {
        // Get the transactions
        var transactions = _searchTransactionsUseCase.Execute(
            cashierName: transactionViewModel.CashierName ?? string.Empty,
            startDate: transactionViewModel.StartDate,
            endDate: transactionViewModel.EndDate);

        transactionViewModel.Transactions = transactions;

        return View(viewName: "Index", model: transactionViewModel);
    }
}

src/WebApp/Views/Shared/_Layout.cshtml
@* Razor view *@

<!doctype html>
<html lang='en'>

<head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <title>Inventory and Sales</title>
    <link href='/lib/bootstrap/css/bootstrap.min.css' rel='stylesheet'>
    <link href='/css/site.css' rel="stylesheet" asp-append-version="true">
</head>

<body>
    <header>
        <div class="d-flex p-2 justify-content-center bg-black text-light">
            Developed by&nbsp;<a class="link-light" href="https://www.github.com/kumailalidev" target="_blank">Kumail
                Ali
                Shaikh</a>
        </div>
        @* Navigation Menu *@
        <nav class="navbar navbar-expand-lg bg-body-tertiary mb-2">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Inventory and Sales App</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <partial name="_NavBar" />
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>

    @* Main content *@
    <div class="container">
        <div>
            @* 'title' section. It is optional section, has to be used by every razor view. *@
            @RenderSection(name: "title", required: false)
            <hr>
        </div>
        <div>
            @* Placeholder for each individual view (razor view) *@
            @RenderBody()
        </div>
    </div>

    @* JavaScript *@
    @* Bootstrap *@
    <script src='/lib/bootstrap/js/bootstrap.bundle.min.js'></script>
    @* JQuery *@
    <script src="https://code.jquery.com/jquery-3.7.1.min.js"
        integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    @await RenderSectionAsync(name: "Scripts", required: false)

</body>

</html>

src/WebApp/Views/Shared/_NavBar.cshtml
@inject SignInManager<IdentityUser> SignInManager

<ul class="navbar-nav flex-grow-1">
    <li class="nav-item">
        <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">Home</a>
    </li>

    @if (SignInManager.IsSignedIn(User))
    {
        // Check claim types for specific roles
        var isAdmin = User.HasClaim(c => c.Type == "Position" && c.Value == "Admin");
        var isSeller = User.HasClaim(c => c.Type == "Position" && c.Value == "Seller");
        var isManager = User.HasClaim(c => c.Type == "Position" && c.Value == "Manager");

        @* Admin Only *@
        @if (isAdmin)
        {
            <li class="nav-item">
                <a class="nav-link" asp-controller="Categories" asp-action="Index">Categories</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" asp-controller="Products" asp-action="Index">Products</a>
            </li>
        }

        @* Admin and Sales *@
        @if (isAdmin || isSeller)
        {
            <li class="nav-item">
                <a class="nav-link" asp-controller="Sales" asp-action="Index">Sales</a>
            </li>
        }

        @* Admin and Manager *@
        @if (isAdmin || isManager)
        {
            <li class="nav-item">
                <a class="nav-link" asp-controller="Transactions" asp-action="Index">Transactions</a>
            </li>
        }
    }
</ul>